name              'osl-nextcloud'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-nextcloud'
issues_url        'https://github.com/osuosl-cookbooks/osl-nextcloud/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-nextcloud'
chef_version      '>= 16.0'
version           '1.0.0'

depends          'osl-apache'
depends          'osl-php'
depends          'osl-repos'

supports 'centos_stream', '~> 8.0'
