name              'osl-nextcloud'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-nextcloud'
issues_url        'https://github.com/osuosl-cookbooks/osl-nextcloud/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-nextcloud'
chef_version      '>= 18.0'
version           '3.0.0'

depends          'ark'
depends          'line'
depends          'osl-apache'
depends          'osl-php'
depends          'osl-repos'
depends          'osl-selinux'

supports 'almalinux', '~> 8.0'
supports 'almalinux', '~> 9.0'
supports 'almalinux', '~> 10.0'
